### ISSUE TITLE
ignorowanie node modules

### ISSUE THREAD

**Issue by zdolny** [TomaszAdamowicz/ProjektKodilla#1]
Katalogu `node_modules` nie trzymaj w repozytorium. Utworz plik `.gitignore` i dodaj do niego ten katalog, aby byl ignorowany. Efekt jaki powinienes osiagnac to brak `node_modules` w repo i po zainstalowaniu paczek lokalnie, utworzony katalog `node_modules` nie powinien byc pokazywany przez gita

**Comment by TomaszAdamowicz** [comment]
Ok, zrobione. Nie kumam o co chodzi z instalowaniem paczek lokalnie :)

**Comment by zdolny** [comment]
jest git :)
