### ISSUE TITLE
wykorzystanie zminifikowanych obrazkow

### ISSUE THREAD

**Issue by zdolny** [TomaszAdamowicz/ProjektKodilla#2]
Masz task w gruncie, ktory minifikuje obrazki i zapisuje je w katalogu img/build - fajnie byloby wykorzystac te zminifikowane wersje obrazkow w pliku html.

Do wykonania tego zadania utworz lokalnie nowy branch od mastera, na nawym branchu dokonaj zmian, zacommituj i wypushuj. Nastepnie na githubie zaloz pull request tego brancha do mastera, a ja te pull request zaakceptuje :)

**Comment by TomaszAdamowicz** [comment]
Ok, powinieneś dostać pull request :)
